### ISSUE TITLE
Vehicle Ownership Check

### ISSUE THREAD

**Issue by WalterLoireMNF** [MaDHouSe79/qb-drifting#1]
As the script doesn't check if the player owns the vehicle or not an another player can enter the vehicle and apply drift kit to make the car go super fast. If its Possible the script should check if the vehicle is owned by the item user or not

**Comment by MaDHouSe79** [comment]
This is not a script for daly use, cause it's made for drifiraces and not to use it daly al over the map, this mod is not made for that. it also not made for roleplay servers, its just a fun script for players who like to do driftraces.

**Comment by WalterLoireMNF** [comment]
Thank you for your quick response. Sorry, didn't know it wasn't originally implemented for roleplay servers. My apologies and very thanks for the commit :)

**Comment by MaDHouSe79** [comment]
oops the check does not work as it has to be, ill fix it when i;m home

**Comment by WalterLoireMNF** [comment]
Yeah, was just about to say it. Thanks a alot mate :) 👍

**Comment by MaDHouSe79** [comment]
check if this works ;)

**Comment by WalterLoireMNF** [comment]
Works like a beauty. Thanks a lot :)

**Comment by WalterLoireMNF** [comment]
Awesome Support. Have a good day sir.

**Comment by MaDHouSe79** [comment]
Thnx you, you to :)
